# Generated by Django 3.0 on 2021-08-06 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='FIRST_NAME', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=10, null=True)),
                ('email_addr', models.CharField(blank=True, db_column='EMAIL_ADDR', max_length=50, null=True)),
                ('street_addr', models.CharField(blank=True, db_column='STREET_ADDR', max_length=100, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
